controller_list:
    - name: mavi_arm_controller
      action_ns: "follow_joint_trajectory"
      type: FollowJointTrajectory 
      joints: [arm_height,horizontal_arm_joint_1,horizontal_arm_joint_2,horizontal_arm_joint_3,vertical_arm_joint_1]
