joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50
mavi_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - arm_height
        - horizontal_arm_joint_1
        - horizontal_arm_joint_2
        - horizontal_arm_joint_3
        - vertical_arm_joint_1
